config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:index, :show, :create, :new]
  resources :histories, only: [:index, :show]
  devise_for :users 
  resources :restaurants, except: [:destroy] do
      put :upvote
      put :downvote
      resources :favorites, only: [:create]
    end
  root 'restaurants#index'
  get '/about' => 'pages#about'
  get '/summary' => 'pages#summary'
  match 'favorite', to: 'favorites#favorite', via: :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant

  def self.search(restaurant_id)
    if restaurant_id
      where('restaurant_id LIKE ?', restaurant_id)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @user = current_user
    @comment = Comment.new(restaurant_id: params[:restaurant_id], user_id: @user.id)
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to restaurant_path(@comment.restaurant.id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:comment, :user_id, :restaurant_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container-fluid">
<div class="row">
    <div class="col-sm-6">
      <table class="table table-responsive">
      <tr>
        <div class="field">
          <td><%= form.label :comment %></td>
          <td><%= form.text_area :comment %></td>
        </div>
      
        <div class="field">
          <%= form.hidden_field :user_id %>
        </div>
        <div class="field">
	  <%= form.hidden_field :restaurant_id %>
        </div>
      </tr>
      <tr>
        <div class="actions">
          <td colspan="2"><%= form.submit %></td>
      </tr>
    </table>
    </div>

<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>
<div class="container">
<%= render 'form', comment: @comment %>

      <table class="table table-responsive">
        <tr>
           <td><%= link_to 'Show', @comment, class: 'btn btn-primary btn-xs' %></td>
           <td><%= link_to 'Back', comments_path, class: 'btn btn-primary btn-xs' %></td>
        </tr>
      </table>

</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Comment</th>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.comment %></td>
        <td><%= comment.user %></td>
        <td><%= comment.restaurant %></td>
        <td><%= link_to 'Show', comment %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<table class="table table-responsive">
      <tr>
        <td><%= link_to 'Back', restaurant_url(@comment.restaurant_id), class: 'btn btn-primary btn-xs' %></td>
      </tr>
      </table>

app/views/comments/show.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-sm-4">
      <table class="table table-responsive">
      <tr>
        <td><strong>Comment:</strong></td>
        <td> <%= @comment.comment %></td>
      </tr>

      <tr>
        <td><strong>User:</strong></td>
        <td> <%= @comment.user.email %></td>
      </tr>

      <tr>
        <td><strong>Restaurant:</strong></td>
        <td> <%= @comment.restaurant.name %></td>
      </tr>
      <tr>
        <td><%= link_to 'Back', restaurant_url(@comment.restaurant_id), class: 'btn btn-primary btn-xs' %></td>
      </tr>
    </table

    </div>
    
  </div>

</div>