config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:index, :show, :create, :new]
  resources :histories, only: [:index, :show]
  devise_for :users 
  resources :restaurants, except: [:destroy] do
      put :upvote
      put :downvote
      resources :favorites, only: [:create]
    end
  root 'restaurants#index'
  get '/about' => 'pages#about'
  get '/summary' => 'pages#summary'
  match 'favorite', to: 'favorites#favorite', via: :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:will_split, :wont_split, :user_id, :restaurant_id)
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/views/histories/_form.html.erb
<%= form_with(model: history, local: true) do |form| %>
  <% if history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :will_split %>
    <%= form.number_field :will_split %>
  </div>

  <div class="field">
    <%= form.label :wont_split %>
    <%= form.number_field :wont_split %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Histories</h1>

<table>
  <thead>
    <tr>
      <th>Will split</th>
      <th>Wont split</th>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.will_split %></td>
        <td><%= history.wont_split %></td>
        <td><%= history.user %></td>
        <td><%= history.restaurant %></td>
        <td><%= link_to 'Show', history %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/histories/new.html.erb
<h1>New History</h1>

<%= render 'form', history: @history %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Will split:</strong>
  <%= @history.will_split %>
</p>

<p>
  <strong>Wont split:</strong>
  <%= @history.wont_split %>
</p>

<p>
  <strong>User:</strong>
  <%= @history.user %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @history.restaurant %>
</p>

<%= link_to 'Back', histories_path %>