config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:index, :show, :create, :new]
  resources :histories, only: [:index, :show]
  devise_for :users 
  resources :restaurants, except: [:destroy] do
      put :upvote
      put :downvote
      resources :favorites, only: [:create]
    end
  root 'restaurants#index'
  get '/about' => 'pages#about'
  get '/summary' => 'pages#summary'
  match 'favorite', to: 'favorites#favorite', via: :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :histories, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  validates :name, :location, presence: true
  validates :name, uniqueness: true
  
  def will_split_vote(user)
    #self.increment! :will_split
    @history = self.histories.create(will_split: 1, user: user)
  end

  def wont_split_vote(user)
    #self.increment! :wont_split
    @history = self.histories.create(wont_split: 1, user: user)
  end

  def self.search(term)
    if term
      where('name LIKE ? OR location LIKE ?', "%#{term}%", "%#{term}%")
    else
      all.sort_by(&:composite_vote).reverse
      #all
    end
  end

  def composite_vote
    if self.histories.sum(:will_split) + self.histories.sum(:wont_split) == 0
      0
    else
      self.histories.sum(:will_split).to_f/(self.histories.sum(:will_split) + self.histories.sum(:wont_split))
    end
  end
   
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:show, :index]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.search(params[:term])
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @comments = Comment.search(@restaurant.id)
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def upvote
    @restaurant = Restaurant.find params[:restaurant_id]
    @user = current_user
    @restaurant.will_split_vote(@user)
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  def downvote
    @restaurant = Restaurant.find params[:restaurant_id]
    @user = current_user
    @restaurant.wont_split_vote(@user)
    respond_to do |format|
      format.html { redirect_to restaurants_url }
      format.json { head :no_content }
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :will_split, :wont_split, :term)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container-fluid">
<div class="row">
    <div class="col-sm-6">
      <table class="table table-responsive">
      <tr>
        <div class="field">
            <td><%= form.label :name %></td>
            <td><%= form.text_field :name %></td>
         </div>

       </tr>
       <tr>
          <div class="field">
            <td><%= form.label :location %></td>
            <td><%= form.text_field :location %></td>
          </div>
        </tr>
        <tr>
          <div class="field">
            <td>Will Split Votes:</td>
            <td><%= @restaurant.histories.sum(:will_split).to_s %></td>
          </div>
        </tr>
         <tr>
          <div class="field">
            <td>Wont Split Votes:</td>
            <td><%= @restaurant.histories.sum(:wont_split).to_s %></td>
          </div>
        </tr>
        <tr>
       
       <tr>
          <td colspan="2"><div class="actions">
              <%= form.submit %>
              </div>
          </td>
        </tr>
     </table>
    </div>

  
<% end %>

app/views/restaurants/about.html.erb
<h1>About Split the Check</h1>
<p>
It started with a dream: a social media site that rates restaurants who split their customers' check.  Now, 10s of reviews later, Split the Check has become a world wide sensation, drawing users from all over the world.</p>
<%= link_to 'Back', restaurants_path, class: 'btn btn-primary btn-xs' %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>
<div class="container">
<%= render 'form', restaurant: @restaurant %>



      <table class="table table-responsive">
      <tr>
        <td><%= link_to 'Show', @restaurant, class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Back', restaurants_path, class: 'btn btn-primary btn-xs' %></td>
      </tr>
      </table>


</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4">
    
    <div class="jumbotron">
      <%= image_tag 'Splitcheck2.jpg', alt: 'Split the Check' %> 
      <div class="search">
          <h1>Search</h1>
          <p>Search restaurants by Name or Location</p>
          <%= form_tag(restaurants_path, method: :get) do %>
          <%= text_field_tag :term, params[:term], id: :search_term %>
          <%= submit_tag 'Search', name: nil %>
          <% end %> 
        
      <h4>Can't find your Restaurant??</h4>
      <% if user_signed_in? %>
        <%= link_to 'Add a New Restaurant', new_restaurant_path, class: 'btn btn-primary btn-lg' %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary btn-lg'  %>
        <h4>Or</h4>
        <%= link_to "Login", new_user_session_path, :class => 'btn btn-primary btn-lg'  %>
        <h4>To Add Your Favorite Check Splitter!!</h4>
      <% end %>
      </div> 
   </div>
    </div>
    <div class="col-sm-8">
    <h1>Restaurant Split Rating</h1>

    <table class="table table-striped">
      <thead>
      <tr>
        <th>&nbsp</th>
        <th>Name</th>
        <th>Location</th>
        <th>Will split</th>
        <th>Wont split</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
        <tr class="restaurant">
          <td>
          <% if user_signed_in? %>
            <% if !current_user.favorite?(restaurant) %>
              <%= button_to "Favorite", favorite_path(restaurant_id: restaurant.id), class: 'btn btn-info btn-xs', method: :post %>
            <% else %>
              <span class="glyphicon glyphicon-star-empty"></span>
              Favorited!
            
          <% end %>
        <% end %>
          </td>
          <td><%= restaurant.name %></td>
          <td><%= restaurant.location %></td>
          <td><%= button_to 'will split votes: ' + restaurant.histories.sum(:will_split).to_s, restaurant_upvote_path(restaurant), method: :put %></td>
          <td><%= button_to 'wont split votes: ' + restaurant.histories.sum(:wont_split).to_s, restaurant_downvote_path(restaurant), method: :put %></td>
          <td><%= link_to 'Show', restaurant, class: 'btn btn-primary btn-xs' %></td>
          
          <% if user_signed_in? %>
            <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-primary btn-xs' %></td>
          <% end %>
          
        </tr>
      <% end %>
    </tbody>
</table>
</div>
</div>
</div>

<br>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<table class="table table-responsive">
      <tr>
        <td><%= link_to 'Back', restaurants_path, class: 'btn btn-primary btn-xs' %></td>
      </tr>
      </table>

app/views/restaurants/show.html.erb
      <table class="table">
      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @restaurant.name %></td>
      </tr>
      <tr>
        <td><strong>Location:</strong></td>
        <td> <%= @restaurant.location %></td>
      </tr>

      <tr>
        <td><strong>Will Split Votes:</strong></td>
        <td> <%= @restaurant.histories.sum(:will_split).to_s %></td>
      </tr>

      <tr>
        <td><strong>Wont Split Votes:</strong></td>
        <td> <%= @restaurant.histories.sum(:wont_split).to_s %></td>
      </tr>
      
      <tr>
          <td><%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-primary btn-xs' %></td>
        <td><%= link_to 'Back', restaurants_path, class: 'btn btn-primary btn-xs' %></td>
      </tr>
      <tr>
       
      
      <tr>
      <td>
      <% if @comments.count > 0 %>
        <h1>Comments</h1>
      <% end %></td>  
      
      <td>
        <% if user_signed_in? %>
          <%= link_to 'Add Comment', new_comment_path(restaurant_id: @restaurant.id, user_id: :current_user), class: 'btn btn-info btn-lg' %>
        <% end %></td>

      </tr>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><b><%= comment.user.email %></b> <i>says:</i> </td>
        <td><%= comment.comment %></td>
        
      </tr>
    <% end %>
  </tbody>

    </table