config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:index, :show, :create, :new]
  resources :histories, only: [:index, :show]
  devise_for :users 
  resources :restaurants, except: [:destroy] do
      put :upvote
      put :downvote
      resources :favorites, only: [:create]
    end
  root 'restaurants#index'
  get '/about' => 'pages#about'
  get '/summary' => 'pages#summary'
  match 'favorite', to: 'favorites#favorite', via: :post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Split The Check: A Social Networking Site that Rates Check-Splitting Restaurants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="main">
      <div class="container">
        
        <nav class="navbar navbar-fixed-top navbar-inverse">
          <%= image_tag 'SplitcheckHeader.jpg', alt: 'Split the Check' %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home", restaurants_path %></li>
            
              <% if user_signed_in? %>
              <li>Logged in as <br><strong><%= current_user.email %></strong></li>
              <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li><%= link_to 'User Summary', summary_path, :class => 'navbar-link' %></li>
             <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
             <% else %>
               <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
               <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
<% end %>

            <li><%= link_to "About", about_path %></li>
          </ul>
        </nav>
          <h1>Split the Check</h1>
          <h2>Rating Restaurants that Split Customer Checks</h2>
      </div>
    </header>
    <section class="content">
      <div class="container">
        <main class='<%= controller.controller_name %>'>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
          <%= yield %>
        </main>
      </div>
    </section>
  </body>
</html>